# Generated by Django 4.2.7 on 2023-12-01 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCalendarApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AlterField(
            model_name='calendar',
            name='Date',
            field=models.DateField(default=datetime.datetime(2023, 12, 1, 15, 24, 40, 276112)),
        ),
    ]
