# Generated by Django 4.2.7 on 2023-12-01 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCalendarApp', '0005_alter_calendar_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='Date',
            field=models.DateField(default=datetime.datetime(2023, 12, 1, 19, 34, 55, 665138)),
        ),
    ]
